---
driver:
  name: terraform
  variable_files:
    - testing.tfvars

provisioner:
  name: terraform

platforms:
  - name: ubuntu

transport:
  name: ssh
  ssh_key: ./bliak.pem 

verifier:
  name: terraform
  systems:
    - name: default
      backend: ssh
      user: ubuntu      
#      hosts: 
#        - "$aws_instance.example.public_dns"
      hosts_output: public_dns
      key_files:
        - ./bliak.pem
suites:
  - name: default


